"""Tests for Go code generator."""

import pytest
from picomsg.schema.ast import (
    Schema, Namespace, Struct, Message, Field, Enum, EnumValue,
    PrimitiveType, StringType, BytesType, ArrayType, FixedArrayType,
    StructType, EnumType,
)
from picomsg.codegen.go import GoCodeGenerator


def _generate(schema):
    gen = GoCodeGenerator(schema)
    files = gen.generate()
    assert len(files) == 1
    content = list(files.values())[0]
    return content


def _make_schema(**kwargs):
    defaults = dict(enums=[], structs=[], messages=[], namespace=None)
    defaults.update(kwargs)
    return Schema(**defaults)


# ── Basic generation ──────────────────────────────────────────────


class TestBasicGeneration:
    def test_single_file_output(self):
        schema = _make_schema(namespace=Namespace("test.example"))
        gen = GoCodeGenerator(schema)
        files = gen.generate()
        assert len(files) == 1
        assert "picomsg_generated.go" in files

    def test_custom_module_name(self):
        schema = _make_schema()
        gen = GoCodeGenerator(schema)
        gen.set_option('module_name', 'my_api')
        files = gen.generate()
        assert "my_api.go" in files
        assert "package my_api" in files["my_api.go"]

    def test_package_declaration(self):
        content = _generate(_make_schema())
        assert "package picomsg_generated" in content

    def test_imports(self):
        content = _generate(_make_schema())
        assert '"bytes"' in content
        assert '"encoding/binary"' in content
        assert '"io"' in content
        assert '"fmt"' in content

    def test_auto_generated_comment(self):
        content = _generate(_make_schema())
        assert "Code generated by PicoMsg. DO NOT EDIT." in content

    def test_namespace_prefix_constants(self):
        schema = _make_schema(namespace=Namespace("test.example"))
        content = _generate(schema)
        assert "TestExampleMagicByte1" in content
        assert "TestExampleVersion" in content
        assert "TestExampleHeaderSize" in content

    def test_no_namespace(self):
        schema = _make_schema(
            structs=[Struct("Point", [Field("x", PrimitiveType("f32"))])]
        )
        content = _generate(schema)
        assert "type Point struct" in content
        assert "MagicByte1" in content

    def test_version_constant(self):
        schema = _make_schema(namespace=Namespace("api"), version=3)
        content = _generate(schema)
        assert "ApiVersion uint8 = 3" in content

    def test_serializer_interface(self):
        content = _generate(_make_schema())
        assert "Serializer interface" in content
        assert "ToBytes() ([]byte, error)" in content
        assert "FromBytes(data []byte) error" in content

    def test_error_variables(self):
        schema = _make_schema(namespace=Namespace("test.example"))
        content = _generate(schema)
        assert "ErrTestExampleInvalidHeader" in content
        assert "ErrTestExampleBufferTooSmall" in content
        assert "ErrTestExampleInvalidData" in content

    def test_helper_functions(self):
        content = _generate(_make_schema())
        assert "func readPrimitive[T any](r io.Reader)" in content
        assert "func writePrimitive[T any](w io.Writer, v T)" in content
        assert "func readString(r io.Reader)" in content
        assert "func writeString(w io.Writer, s string)" in content
        assert "func readBytes(r io.Reader)" in content
        assert "func writeBytes(w io.Writer, data []byte)" in content
        assert "func readBool(r io.Reader)" in content
        assert "func writeBool(w io.Writer, v bool)" in content


# ── Primitive types ───────────────────────────────────────────────


class TestPrimitiveTypes:
    @pytest.mark.parametrize("pico_type,go_type", [
        ("u8", "uint8"), ("i8", "int8"),
        ("u16", "uint16"), ("i16", "int16"),
        ("u32", "uint32"), ("i32", "int32"),
        ("u64", "uint64"), ("i64", "int64"),
        ("f32", "float32"), ("f64", "float64"),
        ("bool", "bool"),
    ])
    def test_primitive_field_type(self, pico_type, go_type):
        schema = _make_schema(
            structs=[Struct("Test", [Field("val", PrimitiveType(pico_type))])]
        )
        content = _generate(schema)
        assert f"Val {go_type}" in content

    @pytest.mark.parametrize("pico_type", [
        "u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64", "f32", "f64",
    ])
    def test_primitive_read_uses_readPrimitive(self, pico_type):
        schema = _make_schema(
            structs=[Struct("Test", [Field("val", PrimitiveType(pico_type))])]
        )
        content = _generate(schema)
        assert "readPrimitive[" in content

    @pytest.mark.parametrize("pico_type", [
        "u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64", "f32", "f64",
    ])
    def test_primitive_write_uses_writePrimitive(self, pico_type):
        schema = _make_schema(
            structs=[Struct("Test", [Field("val", PrimitiveType(pico_type))])]
        )
        content = _generate(schema)
        assert "writePrimitive(w, s.Val)" in content

    def test_bool_read(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("flag", PrimitiveType("bool"))])]
        )
        content = _generate(schema)
        assert "readBool(r)" in content

    def test_bool_write(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("flag", PrimitiveType("bool"))])]
        )
        content = _generate(schema)
        assert "writeBool(w, s.Flag)" in content


# ── String and bytes ──────────────────────────────────────────────


class TestStringAndBytes:
    def test_string_field_type(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("name", StringType())])]
        )
        content = _generate(schema)
        assert "Name string" in content

    def test_string_read(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("name", StringType())])]
        )
        content = _generate(schema)
        assert "readString(r)" in content

    def test_string_write(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("name", StringType())])]
        )
        content = _generate(schema)
        assert "writeString(w, s.Name)" in content

    def test_bytes_field_type(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("data", BytesType())])]
        )
        content = _generate(schema)
        assert "Data []byte" in content

    def test_bytes_read(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("data", BytesType())])]
        )
        content = _generate(schema)
        assert "readBytes(r)" in content

    def test_bytes_write(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("data", BytesType())])]
        )
        content = _generate(schema)
        assert "writeBytes(w, s.Data)" in content


# ── Arrays ────────────────────────────────────────────────────────


class TestArrays:
    def test_variable_array_field_type(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("items", ArrayType(PrimitiveType("u32")))])]
        )
        content = _generate(schema)
        assert "Items []uint32" in content

    def test_variable_array_write_count(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("items", ArrayType(PrimitiveType("u32")))])]
        )
        content = _generate(schema)
        assert "writePrimitive(w, uint16(len(s.Items)))" in content

    def test_variable_array_read_count(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("items", ArrayType(PrimitiveType("u32")))])]
        )
        content = _generate(schema)
        assert 'count, err := readPrimitive[uint16](r)' in content
        assert "make([]uint32, count)" in content

    def test_fixed_array_field_type(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("rgb", FixedArrayType(PrimitiveType("u8"), 3))])]
        )
        content = _generate(schema)
        assert "Rgb [3]uint8" in content

    def test_fixed_array_no_count_prefix(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("rgb", FixedArrayType(PrimitiveType("u8"), 3))])]
        )
        content = _generate(schema)
        # Fixed arrays iterate a fixed number of times, no count written
        assert "for i := 0; i < 3; i++" in content

    def test_string_array(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("names", ArrayType(StringType()))])]
        )
        content = _generate(schema)
        assert "Names []string" in content

    def test_fixed_string_array(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("tags", FixedArrayType(StringType(), 5))])]
        )
        content = _generate(schema)
        assert "Tags [5]string" in content

    def test_struct_array(self):
        schema = _make_schema(
            namespace=Namespace("api"),
            structs=[
                Struct("point", [Field("x", PrimitiveType("f32"))]),
                Struct("path", [Field("points", ArrayType(StructType("point")))]),
            ]
        )
        content = _generate(schema)
        assert "Points []ApiPoint" in content

    def test_bytes_array(self):
        schema = _make_schema(
            structs=[Struct("Test", [Field("chunks", ArrayType(BytesType()))])]
        )
        content = _generate(schema)
        assert "Chunks [][]byte" in content


# ── Enums ─────────────────────────────────────────────────────────


class TestEnums:
    def test_enum_type_definition(self):
        schema = _make_schema(
            enums=[Enum("status", PrimitiveType("u8"), [
                EnumValue("Active", 1), EnumValue("Inactive", 0),
            ])]
        )
        content = _generate(schema)
        assert "type Status uint8" in content

    def test_enum_constants(self):
        schema = _make_schema(
            enums=[Enum("status", PrimitiveType("u8"), [
                EnumValue("Active", 1), EnumValue("Inactive", 0),
            ])]
        )
        content = _generate(schema)
        assert "StatusActive Status = 1" in content
        assert "StatusInactive Status = 0" in content

    def test_enum_from_value(self):
        schema = _make_schema(
            enums=[Enum("status", PrimitiveType("u16"), [
                EnumValue("Active", 1),
            ])]
        )
        content = _generate(schema)
        assert "func StatusFromValue(v uint16) (Status, error)" in content

    def test_enum_string_method(self):
        schema = _make_schema(
            enums=[Enum("status", PrimitiveType("u8"), [
                EnumValue("Active", 1),
            ])]
        )
        content = _generate(schema)
        assert "func (e Status) String() string" in content

    def test_enum_with_namespace(self):
        schema = _make_schema(
            namespace=Namespace("my.app"),
            enums=[Enum("priority", PrimitiveType("u8"), [
                EnumValue("Low", 1), EnumValue("High", 10),
            ])]
        )
        content = _generate(schema)
        assert "type MyAppPriority uint8" in content
        assert "MyAppPriorityLow MyAppPriority = 1" in content
        assert "MyAppPriorityHigh MyAppPriority = 10" in content

    def test_enum_field_read(self):
        schema = _make_schema(
            enums=[Enum("priority", PrimitiveType("u8"), [
                EnumValue("Low", 1), EnumValue("High", 10),
            ])],
            structs=[Struct("task", [Field("prio", EnumType("priority"))])]
        )
        content = _generate(schema)
        assert "readPrimitive[uint8](r)" in content
        assert "PriorityFromValue(v)" in content

    def test_enum_field_write(self):
        schema = _make_schema(
            enums=[Enum("priority", PrimitiveType("u8"), [
                EnumValue("Low", 1), EnumValue("High", 10),
            ])],
            structs=[Struct("task", [Field("prio", EnumType("priority"))])]
        )
        content = _generate(schema)
        assert "writePrimitive(w, uint8(s.Prio))" in content

    def test_enum_backing_types(self):
        for backing in ["u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64"]:
            go_type = backing.replace("u", "uint").replace("i", "int")
            if backing.startswith("u"):
                go_type = backing.replace("u", "uint")
            else:
                go_type = backing.replace("i", "int")
            schema = _make_schema(
                enums=[Enum("test_enum", PrimitiveType(backing), [EnumValue("Val", 1)])]
            )
            content = _generate(schema)
            assert f"type TestEnum {go_type}" in content


# ── Structs ───────────────────────────────────────────────────────


class TestStructs:
    def test_struct_definition(self):
        schema = _make_schema(
            structs=[Struct("point", [
                Field("x", PrimitiveType("f32")),
                Field("y", PrimitiveType("f32")),
            ])]
        )
        content = _generate(schema)
        assert "type Point struct" in content
        assert "X float32" in content
        assert "Y float32" in content

    def test_struct_methods(self):
        schema = _make_schema(
            structs=[Struct("point", [Field("x", PrimitiveType("f32"))])]
        )
        content = _generate(schema)
        assert "func (s *Point) ToBytes() ([]byte, error)" in content
        assert "func (s *Point) FromBytes(data []byte) error" in content
        assert "func (s *Point) WriteTo(w io.Writer) error" in content
        assert "func (s *Point) ReadFrom(r io.Reader) error" in content

    def test_nested_struct(self):
        schema = _make_schema(
            namespace=Namespace("api"),
            structs=[
                Struct("point", [
                    Field("x", PrimitiveType("f32")),
                    Field("y", PrimitiveType("f32")),
                ]),
                Struct("line", [
                    Field("start", StructType("point")),
                    Field("end", StructType("point")),
                ]),
            ]
        )
        content = _generate(schema)
        assert "Start ApiPoint" in content
        assert "End ApiPoint" in content
        assert "s.Start.WriteTo(w)" in content
        assert "s.Start.ReadFrom(r)" in content

    def test_struct_with_namespace(self):
        schema = _make_schema(
            namespace=Namespace("my.api"),
            structs=[Struct("sensor_data", [Field("value", PrimitiveType("f64"))])]
        )
        content = _generate(schema)
        assert "type MyApiSensorData struct" in content


# ── Messages ──────────────────────────────────────────────────────


class TestMessages:
    def test_message_type_id(self):
        schema = _make_schema(
            namespace=Namespace("api"),
            messages=[
                Message("ping", [Field("seq", PrimitiveType("u32"))]),
                Message("pong", [Field("seq", PrimitiveType("u32"))]),
            ]
        )
        content = _generate(schema)
        assert "ApiPingTypeID uint16 = 1" in content
        assert "ApiPongTypeID uint16 = 2" in content

    def test_message_struct_and_methods(self):
        schema = _make_schema(
            messages=[Message("echo", [Field("payload", StringType())])]
        )
        content = _generate(schema)
        assert "type Echo struct" in content
        assert "func (s *Echo) ToBytes()" in content
        assert "func (s *Echo) FromBytes(" in content
        assert "func (s *Echo) WriteTo(" in content
        assert "func (s *Echo) ReadFrom(" in content


# ── Complex schemas ───────────────────────────────────────────────


class TestComplexSchemas:
    def test_all_field_types_together(self):
        schema = _make_schema(
            namespace=Namespace("test"),
            enums=[Enum("color", PrimitiveType("u8"), [
                EnumValue("Red", 0), EnumValue("Green", 1), EnumValue("Blue", 2),
            ])],
            structs=[
                Struct("point", [
                    Field("x", PrimitiveType("f32")),
                    Field("y", PrimitiveType("f32")),
                ]),
                Struct("complex", [
                    Field("id", PrimitiveType("u64")),
                    Field("name", StringType()),
                    Field("data", BytesType()),
                    Field("flag", PrimitiveType("bool")),
                    Field("pos", StructType("point")),
                    Field("shade", EnumType("color")),
                    Field("scores", ArrayType(PrimitiveType("f64"))),
                    Field("tags", FixedArrayType(StringType(), 3)),
                    Field("matrix", FixedArrayType(PrimitiveType("u8"), 4)),
                ]),
            ]
        )
        content = _generate(schema)
        # Verify all types present
        assert "Id uint64" in content
        assert "Name string" in content
        assert "Data []byte" in content
        assert "Flag bool" in content
        assert "Pos TestPoint" in content
        assert "Shade TestColor" in content
        assert "Scores []float64" in content
        assert "Tags [3]string" in content
        assert "Matrix [4]uint8" in content

    def test_enum_array(self):
        schema = _make_schema(
            enums=[Enum("priority", PrimitiveType("u8"), [
                EnumValue("Low", 0), EnumValue("High", 1),
            ])],
            structs=[Struct("task_list", [
                Field("priorities", ArrayType(EnumType("priority"))),
            ])]
        )
        content = _generate(schema)
        assert "Priorities []Priority" in content
        assert "PriorityFromValue(v)" in content

    def test_fixed_enum_array(self):
        schema = _make_schema(
            enums=[Enum("priority", PrimitiveType("u8"), [
                EnumValue("Low", 0), EnumValue("High", 1),
            ])],
            structs=[Struct("task_triple", [
                Field("priorities", FixedArrayType(EnumType("priority"), 3)),
            ])]
        )
        content = _generate(schema)
        assert "Priorities [3]Priority" in content

    def test_fixed_struct_array(self):
        schema = _make_schema(
            namespace=Namespace("geo"),
            structs=[
                Struct("point", [Field("x", PrimitiveType("f32"))]),
                Struct("triangle", [
                    Field("vertices", FixedArrayType(StructType("point"), 3)),
                ]),
            ]
        )
        content = _generate(schema)
        assert "Vertices [3]GeoPoint" in content

    def test_struct_array_serialization(self):
        schema = _make_schema(
            namespace=Namespace("api"),
            structs=[
                Struct("item", [Field("id", PrimitiveType("u32"))]),
                Struct("container", [
                    Field("items", ArrayType(StructType("item"))),
                ]),
            ]
        )
        content = _generate(schema)
        # Write: call WriteTo on each item
        assert "item.WriteTo(w)" in content
        # Read: call ReadFrom on each item
        assert "ReadFrom(r)" in content


# ── Keyword sanitization ─────────────────────────────────────────


class TestKeywordSanitization:
    def test_sanitize_go_keywords(self):
        gen = GoCodeGenerator(_make_schema())
        assert gen._sanitize_identifier("type") == "type_"
        assert gen._sanitize_identifier("func") == "func_"
        assert gen._sanitize_identifier("map") == "map_"
        assert gen._sanitize_identifier("range") == "range_"
        assert gen._sanitize_identifier("interface") == "interface_"
        assert gen._sanitize_identifier("struct") == "struct_"
        assert gen._sanitize_identifier("chan") == "chan_"

    def test_non_keyword_passes_through(self):
        gen = GoCodeGenerator(_make_schema())
        assert gen._sanitize_identifier("name") == "name"
        assert gen._sanitize_identifier("value") == "value"
